### ISSUE TITLE
Hackage Revision for `text-icu` Version Bump?

### ISSUE THREAD

**Issue by prikhi** [erochest/text-regex-replace#11]
@erochest Any chance we can get a cabal revision published on hackage that includes the recent `text-icu` version bump? Stackage just released LTS 20 & this package has dropped out of it because the `text-icu` upper bound on the hackage version of this package.

**Comment by erochest** [comment]
Yep! I should have a chance to take care of that in the next couple of weeks. Thanks for putting it on my radar.

**Comment by erochest** [comment]
Here you go. Let me know if this doesn't take care of it. https://hackage.haskell.org/package/text-regex-replace-0.1.1.5

**Comment by prikhi** [comment]
Looks great, thanks. Made an MR to bring this back into stackage: https://github.com/commercialhaskell/stackage/pull/6783
