### ISSUE TITLE
Allow latest version of attoparsec as a dependency

### ISSUE THREAD

**Issue by benstevens48** [erochest/text-regex-replace#4]
Hi,
Is it possible to allow the latest version of attoparsec (0.13.0.1) as a dependency?
It's not a problem for me now, but I can see it becoming a problem soon.
Thanks

**Comment by erochest** [comment]
This should be fixed in 9ad44a8c6cd3bd60a3c45521bdda24eacdaf8902, and it's up on Hackage as [text-regex-replace-0.1.1.1](https://hackage.haskell.org/package/text-regex-replace-0.1.1.1).

It passes tests, but please let me know if there's a problem with it.

**Comment by benstevens48** [comment]
Thanks for the quick update!
